### ISSUE TITLE
Problem appear

### ISSUE THREAD

**Issue by reaCodes** [petrkle/empty-new-tab#2]
A long time ago is like this

![qq 20180125121839](https://user-images.githubusercontent.com/13817254/35370798-275eca44-01cb-11e8-8aab-448c0d914197.png)

But upgrading to chrome 64.0.3282.119 becomes like this

![qq 20180125122654](https://user-images.githubusercontent.com/13817254/35370799-2793d450-01cb-11e8-9688-3d71e568c94a.png)

Do you know why?

**Comment by petrkle** [comment]
Fixed in 221c5b55ab2a43b09616281aac07ff0acdd23a9d

**Comment by reaCodes** [comment]
Title value is blank, I think this is not very beautiful.
Can not according to different language environment to give title different value?
For example,
When the system language is English, the title value is set to ' New Tab '
![qq 20180207141113](https://user-images.githubusercontent.com/13817254/35901275-ce05849c-0c10-11e8-827c-54832aa40f4e.png)

When the system language is Chinese, the title value is set to ' 新标签页 '
![image](https://user-images.githubusercontent.com/13817254/35901295-e8321aba-0c10-11e8-9b19-7c858e04afa7.png)

etc.
This design is the same as chrome's default ' New Tab ' title value.

**Comment by petrkle** [comment]
Yes, you right. But this quick dirty fix work for me now. Adding locales increase complexity of this simple extension. Maybe in future.

**Comment by reaCodes** [comment]
I have a question, 
the title value of 0.1 version is blank, but the 'New Tab' title value is automatically set to 'New Tab' after the extension is run,
However, after the 64 version there is no such effect, you must give the title a value, and why?
